{{- if .Values.serviceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "foundationdb-exporter.fullname" . }}
  labels:
    {{- include "foundationdb-exporter.labels" . | nindent 4 }}
spec:
  endpoints:
    - interval: 10s
      port: http
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "foundationdb-exporter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
